langauge: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
  chrome: stable
dist: xenial
before_install:
- gem install bundler
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Um6p1WOEvHkOqum0G0h3f1e4RT1qHgRTO8mXgPyakw40dlc50ZNFGpftXaJqicYK+COhS2rlaJSVLOD7cAkOCwhJmaWdUdknxHCKydY+nnQvM0P/0mqI8hQGkb5sqXGkgqVaseep84D2lL9oLpOqJhQ541stFemlZOoVeuztj78HoAcHIZFV9j4EZ8kHwnY9leLXFAgQLpa38FptIZ//5LW44ui8hdBaYc9BraSJlROpCJxknuKiuHPCV27wZCh81ArSvh/087Q1whbBa0hNFj5sGAv9382UgWrHcfXdeMH+mc5MGJ/yhGZSGuzhBjDXomnz2bs3tKk8E0enR2QqC2f7LaGl5bqVy/kgzWQhA25W2dCDyaJy0zAU4R5+dKP0sZSxBDTKrgS1NotJGPJJPljbcY00qerKi7n9n5diJQb1De84a8s5oEBVMYswoYYKJBQz2QTgKiFp6VKCRjbLO3NFIPapR+e9pcaQFX1tQ4USfW4WQTKYwopZJdeZq60Dko8WrC2o8G5VyIxe6AfXurfzU+/SB6aEJSAymSf3QLowqoSqc23uhQKwvBQO71MqOb+yjweVeTMQCWwF9EPbI56OvoKEf8zvrJeQkrIFjv1Oy8ofczbEUtKrFLJwTt5G9k3FFOG2PJGYLAARdjDjhzbHA4CqglY3NAjcsQXzlSU=
  app: still-escarpment-54514
  on:
    repo: sejinkim1904/brownfield_2
  skip_cleanup: 'true'
