langauge: ruby
rbenv:
- 2.4.1
addons:
  postgresql: 9.6
  chrome: stable
dist: trusty
sudo: false
script:
- yarn
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: dev2S1GhKU5fVwVN8FK1AFWQR1C69h9dKH0DoPrNugZkKVnvhRSZzvwDlG8r7QGjkKBOVh2u3aBSqZRerkWeWaGhir+b+E5dFfIa1WDa4PXbmsfNBnshChQ3HHqWzvDvc1Uw5pB2tR2DRBd4T+vuNkli6aANhyEgC1sGTKlxci7RDYSnJgfLnhtL6nqYsk6N8Na+UDHZ3u/BB7Pjylegk3LMf5NuRseO819v+sBE3EH4OTSndQ9xlfDal02DhP/STMmGKmJi1aQgJmA4aKBvXAeNQJmGWQwGCEIiW5UDutdI1tpLJz+u9TFb1/KKyu+2LGpIkPArmv0cdDkfbgC74gsCvNrSWzEb78xGnUTnS1NIoqJH81Qxcz9xtoJojSvY9kKkDjlfFwRA6Sme9k95B4q+e0KsxfP5mGjW8zRswr88v5hw12QmLZFaJMhQ63UJPWLOWl21AIgeXPyfDe/OffcsQpqh838KbAlyqKcN2dTvgub0Jo2wLy9Cb3JnBAD+7JQ+j4CuD1cVPIHjOvSLXqn4Vq4REe7UkD2YQZ/klYBCUfCClrSRSNqIW6Mpot4z5x0IK83kLOXVL9iN1kcEJM++JqwNlpT3EqMc6DAPTYNFhA9Udul2Js2OSUMjm47e+67TUfKoK5z9/tES3SAp/PL3KM2Bm5BcMmv9uwFVBis=
  app: still-escarpment-54514
  run: rails db:migrate
